# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-18 19:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.FileField(default=0, upload_to='')),
                ('ex', models.IntegerField(default=50)),
                ('sex', models.IntegerField(default=0)),
                ('birthday', models.CharField(max_length=20, null=True)),
                ('touxiang', models.CharField(max_length=200, null=True)),
                ('payment', models.CharField(default='000000', max_length=6)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('is_default', models.IntegerField(default=0)),
                ('conname', models.CharField(max_length=12)),
                ('telephone', models.CharField(max_length=11)),
                ('particulars', models.CharField(max_length=200, null=True)),
                ('uid', models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('productID', models.CharField(max_length=12)),
                ('cname', models.CharField(max_length=64)),
                ('data', models.DateTimeField(null=True)),
                ('number', models.IntegerField(default=0)),
                ('color', models.CharField(default='白色|黑色', max_length=32)),
                ('size', models.CharField(default='L|XL|M|S', max_length=32)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'clothing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClothingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview1', models.CharField(max_length=255, null=True)),
                ('preview2', models.CharField(max_length=255, null=True)),
                ('preview3', models.CharField(max_length=255, null=True)),
                ('preview4', models.CharField(max_length=255, null=True)),
                ('preview5', models.CharField(max_length=255, null=True)),
                ('drawing', models.CharField(max_length=255, null=True)),
                ('detailed', models.CharField(max_length=255, null=True)),
                ('modeled', models.CharField(max_length=255, null=True)),
                ('cid', models.OneToOneField(blank=True, db_column='cid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='front.Clothing')),
            ],
            options={
                'db_table': 'clothingdetail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0.0)),
                ('deadline', models.DateTimeField(null=True)),
                ('cid', models.ForeignKey(blank=True, db_column='cid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='front.Clothing')),
            ],
            options={
                'db_table': 'discount',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=10, null=True)),
                ('number', models.IntegerField(default=1, null=True)),
                ('is_status', models.IntegerField(default=0)),
                ('is_payment', models.IntegerField(default=0)),
                ('is_take', models.IntegerField(default=0)),
                ('is_back', models.IntegerField(default=0)),
                ('shouname', models.CharField(max_length=16)),
                ('shouphone', models.CharField(max_length=11)),
                ('order_address', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(null=True)),
                ('payment_time', models.DateTimeField(null=True)),
                ('cid', models.ForeignKey(blank=True, db_column='cid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='front.Clothing')),
                ('uid', models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestcode', models.CharField(max_length=16)),
                ('requesttime', models.DateTimeField(null=True)),
                ('requesttype', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('oid', models.ForeignKey(blank=True, db_column='oid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='front.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20, null=True)),
                ('grade', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShopCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('money', models.FileField(null=True, upload_to='')),
                ('cid', models.ForeignKey(blank=True, db_column='cid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='front.Clothing')),
                ('uid', models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopcat',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='clothing',
            name='sid',
            field=models.ForeignKey(blank=True, db_column='sid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='front.Section'),
        ),
    ]
