# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-18 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='salesreturn',
            table='salesreturn',
        ),
    ]
