# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-18 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20190918_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='is_del',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='uid',
            field=models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
